# Player Attribute Ratings System
---
This file is to be used to calculate the z scores within a single league for selected positions and minutes played

The export can be used to identify where players within the league excel and then used to create positional profiles

### Setup and Inputs

In [11]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from datetime import datetime

In [12]:
# Load the latest Wyscout dataset available

df = pd.read_csv("Wyscout_League_Export 2026-04-14.csv")

In [13]:
# Create list of unique leagues within dataset

list_unique_leagues = list( sorted( df['League'].unique() ) )
list_unique_leagues

['Albania Superiore League 2024-25',
 'Albania Superiore League 2025-26',
 'Argentina Primera Division 2025',
 'Argentina Primera Division 2026',
 'Australia A-League 2024-25',
 'Australia A-League 2025-26',
 'Austria Bundesliga 2024-25',
 'Austria Bundesliga 2025-26',
 'Belgium First Division A 2024-25',
 'Belgium First Division A 2025-26',
 'Belgium First Division B 2024-25',
 'Belgium First Division B 2025-26',
 'Bolivia Primera Division 2025',
 'Bosnia Premijer Liga 2024-25',
 'Bosnia Premijer Liga 2025-26',
 'Brazil Serie A 2025',
 'Brazil Serie A 2026',
 'Brazil Serie B 2025',
 'Brazil Serie B 2026',
 'Bulgaria First League 2024-25',
 'Bulgaria First League 2025-26',
 'Canada Premier League 2025',
 'Chile Primera Division 2025',
 'Chile Primera Division 2026',
 'China Super League 2025',
 'China Super League 2026',
 'Colombia Primera A 2025',
 'Colombia Primera A 2026',
 'Costa Rica Primera Division 2024-25',
 'Costa Rica Primera Division 2025-26',
 'Croatia 1.HNL 2024-25',
 'Croatia 1.HNL 2025-26',
 'Cyprus First Division 2024-25',
 'Cyprus First Division 2025-26',
 'Czech Fortuna Liga 2024-25',
 'Czech Fortuna Liga 2025-26',
 'Denmark 1st Division 2024-25',
 'Denmark 1st Division 2025-26',
 'Denmark Superliga 2024-25',
 'Denmark Superliga 2025-26',
 'Ecuador Serie A 2025',
 'Ecuador Serie A 2026',
 'Egypt Premier League 2024-25',
 'Egypt Premier League 2025-26',
 'England Championship 2024-25',
 'England Championship 2025-26',
 'England League One 2024-25',
 'England League One 2025-26',
 'England League Two 2024-25',
 'England League Two 2025-26',
 'England National League 2024-25',
 'England National League 2025-26',
 'England National League North South 2024-25',
 'England National League North South 2025-26',
 'England Premier League 2024-25',
 'England Premier League 2025-26',
 'Estonia Meistriliiga 2025',
 'Estonia Meistriliiga 2026',
 'Finland Veikkausliiga 2025',
 'France Championnat National 2024-25',
 'France Championnat National 2025-26',
 'France Ligue 1 2024-25',
 'France Ligue 1 2025-26',
 'France Ligue 2 2024-25',
 'France Ligue 2 2025-26',
 'Georgia Erovnuli Liga 2025',
 'Georgia Erovnuli Liga 2026',
 'Germany 2. Bundesliga 2024-25',
 'Germany 2. Bundesliga 2025-26',
 'Germany 3. Liga 2024-25',
 'Germany 3. Liga 2025-26',
 'Germany Bundesliga 2024-25',
 'Germany Bundesliga 2025-26',
 'Greece Super League 2024-25',
 'Greece Super League 2025-26',
 'Hungary NB1 2024-25',
 'Hungary NB1 2025-26',
 'Indonesia Liga 1 2024-25',
 'Indonesia Liga 1 2025-26',
 'Ireland First Division 2025',
 'Ireland First Division 2026',
 'Ireland Premier Division 2025',
 'Ireland Premier Division 2026',
 "Israel Ligat Ha'Al 2024-25",
 "Israel Ligat Ha'Al 2025-26",
 'Italy Campionato Primavera 1 2024-25',
 'Italy Campionato Primavera 1 2025-26',
 'Italy Serie A 2024-25',
 'Italy Serie A 2025-26',
 'Italy Serie B 2024-25',
 'Italy Serie B 2025-26',
 'Japan J1 100 Year Vision League 2026',
 'Japan J1-League 2025',
 'Japan J2-J3 100 Year Vision League 2026',
 'Japan J2-League 2025',
 'Kazakhstan Premier League 2025',
 'Kazakhstan Premier League 2026',
 'Korea K-League 1 2025',
 'Korea K-League 1 2026',
 'Korea K-League 2 2025',
 'Korea K-League 2 2026',
 'Latvia Virsliga 2025',
 'Latvia Virsliga 2026',
 'Malaysia Super League 2024-25',
 'Malaysia Super League 2025-26',
 'Mexico Liga MX 2024-25',
 'Mexico Liga MX 2025-26',
 'Mexico Liga de Expansion 2024-25',
 'Mexico Liga de Expansion 2025-26',
 'Morocco Botola Pro 2024-25',
 'Morocco Botola Pro 2025-26',
 'Netherlands Eerste Divisie 2024-25',
 'Netherlands Eerste Divisie 2025-26',
 'Netherlands Eredivisie 2024-25',
 'Netherlands Eredivisie 2025-26',
 'Northern Ireland Premiership 2024-25',
 'Northern Ireland Premiership 2025-26',
 'Norway Eliteserien 2025',
 'Norway Eliteserien 2026',
 'Norway First Division 2025',
 'Paraguay Primera Division 2025',
 'Paraguay Primera Division 2026',
 'Peru Primera Division 2025',
 'Peru Primera Division 2026',
 'Poland 1 Liga 2024-25',
 'Poland 1 Liga 2025-26',
 'Poland Ekstraklasa 2024-25',
 'Poland Ekstraklasa 2025-26',
 'Portugal Primeira Liga 2024-25',
 'Portugal Primeira Liga 2025-26',
 'Portugal Segunda Liga 2024-25',
 'Portugal Segunda Liga 2025-26',
 'Romania SuperLiga 2024-25',
 'Romania SuperLiga 2025-26',
 'Russia Premier League 2024-25',
 'Russia Premier League 2025-26',
 'Scotland Championship 2024-25',
 'Scotland Championship 2025-26',
 'Scotland League One 2024-25',
 'Scotland League One 2025-26',
 'Scotland League Two 2024-25',
 'Scotland League Two 2025-26',
 'Scotland Premiership 2024-25',
 'Scotland Premiership 2025-26',
 'Serbia Prva Liga 2025-26',
 'Serbia Super Liga 2024-25',
 'Serbia Super Liga 2025-26',
 'Slovakia Super Liga 2024-25',
 'Slovakia Super Liga 2025-26',
 'Slovenia Prva Liga 2024-25',
 'Slovenia Prva Liga 2025-26',
 'South Africa PSL 2024-25',
 'South Africa PSL 2025-26',
 'Spain La Liga 2024-25',
 'Spain La Liga 2025-26',
 'Spain Primera Division RFEF 2024-25',
 'Spain Primera Division RFEF 2025-26',
 'Spain Segunda 2024-25',
 'Spain Segunda 2025-26',
 'Sweden Allsvenskan 2025',
 'Switzerland Challenge League 2024-25',
 'Switzerland Challenge League 2025-26',
 'Switzerland Super League 2024-25',
 'Switzerland Super League 2025-26',
 'Turkey Super Lig 2024-25',
 'Turkey Super Lig 2025-26',
 'USA MLS 2025',
 'USA MLS 2026',
 'USA MLS Next Pro 2025',
 'USA MLS Next Pro 2026',
 'USA USL Championship 2025',
 'USA USL Championship 2026',
 'USA USL League 1 2025',
 'USA USL League 1 2026',
 'Ukraine Premier League 2024-25',
 'Ukraine Premier League 2025-26',
 'Uruguay Primera Division 2025',
 'Uruguay Primera Division 2026',
 'Uzbekistan Super League 2025',
 'Uzbekistan Super League 2026',
 'Venezuela Primera Division 2025',
 'Venezuela Primera Division 2026']

In [34]:
# Filter settings used later in code

filter_positions = ["CB", "LCB", "RCB"]
filter_leagues = ['England League Two 2025-26']
filter_minutes = 450

# Columns to exclude from the Z-Score Calculation
excluded_columns = ['Player', 'Team', 'Team within selected timeframe', 'Position','Age', 'Market value', 'Contract expires', 'Matches played', 'Minutes played','Birth country', 'Passport country', 'Foot', 'Height', 'Weight', 'On loan','League', 'Main Position']

# Export names
zscore_export_name = "CUFC Z Scores - CB.csv"

### Calculate Z-Scores and Export Data for Review

In [35]:
# Create filtered df prior to applying the filters
filtered_df = df.copy()

# Apply filters to the filtered df
filtered_df = filtered_df[ filtered_df['League'].isin(filter_leagues) ]             # filter leagues
filtered_df = filtered_df[ filtered_df['Main Position'].isin(filter_positions) ]    # filter position
filtered_df = filtered_df[ filtered_df['Minutes played'] >= filter_minutes ]        # filter minutes played

filtered_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
19334,E. Monthe,Oldham Athletic,Oldham Athletic,LCB,31.0,225000,30/06/2026,42,4207,2,...,NaN,NaN,0.04,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19338,N. Smith,Tranmere Rovers,Tranmere Rovers,"CB, LCB, RCB",30.0,450000,30/06/2027,42,4191,3,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,CB
19339,J. Bedeau,Notts County,Notts County,LCB,26.0,325000,30/06/2027,42,4159,0,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19341,J. Tucker,Colchester United,Colchester United,RCB,26.0,275000,30/06/2027,41,4141,2,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,RCB
19342,C. McJannett,Grimsby Town,Grimsby Town,LCB,27.0,175000,30/06/2027,41,4125,1,...,NaN,NaN,0.02,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,0,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,CB
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,0,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,RCB
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,1,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,2,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,0,...,NaN,NaN,0.00,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB

In [36]:
# Calculate the z-scores for all metric columns

z_score_df = filtered_df.copy() # create a new df that is a copy of the filtered df

columns_to_zscore = [col for col in filtered_df.columns if col not in excluded_columns] # creates a list of all columns that are not in the excluded list, i.e. a list of columns to convert into z-scores

z_score_df[columns_to_zscore] = z_score_df[columns_to_zscore].apply(zscore) # takes the metric columns subset of the filtered_df, calculates the z-score for each data point and replaces the absolute value with the z-score

# the apply function works column-wise by default - i.e. for each column, calculate the z-score for each value in the column
# then it is assign back into the original filtered_df. This only works because the output (z-scores) are the same length as the input (filtered_df)

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
19334,E. Monthe,Oldham Athletic,Oldham Athletic,LCB,31.0,225000,30/06/2026,42,4207,0.646104,...,NaN,NaN,-0.094171,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB
19338,N. Smith,Tranmere Rovers,Tranmere Rovers,"CB, LCB, RCB",30.0,450000,30/06/2027,42,4191,1.400899,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,CB
19339,J. Bedeau,Notts County,Notts County,LCB,26.0,325000,30/06/2027,42,4159,-0.863485,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB
19341,J. Tucker,Colchester United,Colchester United,RCB,26.0,275000,30/06/2027,41,4141,0.646104,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,RCB
19342,C. McJannett,Grimsby Town,Grimsby Town,LCB,27.0,175000,30/06/2027,41,4125,-0.108690,...,NaN,NaN,-0.160303,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,-0.863485,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,CB
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,-0.863485,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,RCB
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,-0.108690,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,0.646104,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,-0.863485,...,NaN,NaN,-0.226434,-0.214854,-0.267055,-0.169765,-0.120873,-0.120873,England League Two 2025-26,LCB

In [37]:
# Export the df to CSV
z_score_df.to_csv(zscore_export_name, index=False)
print(f"Z Scores exported {datetime.now().strftime('%d-%m-%Y %H:%M')}")

Z Scores exported 20-04-2026 19:41